#!/usr/bin/env python
#
# Defines constants used in our client-server
# messaging protocol.
#

CREATE_NEW_GAME_MSG = 'CREATE_NEW_GAME'
NEW_GAME_CREATED_MSG = 'NEW_GAME_CREATED'
AWAITING_NEXT_MOVE_MSG = 'AWAITING_NEXT_MOVE'
SUBMIT_MOVE_MSG = 'SUBMIT_MOVE'
GAME_OVER_MSG = 'GAME_OVER'
DO_NOT_RECONNECT = 1001

CODE_GAMES_DOES_NOT_EXIST = 1002
CODE_TEAM_NOT_AUTHORIZED = 1003
CODE_CONCURRENT_MOVE = 1004
CODE_GAME_OVER = 1005
